=== prianti29/api-automation-accelerator-playwright/schemas/petSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Pet",
  "type": "object",
  "required": [
    "name",
    "photoUrls"
  ],
  "properties": {
    "id": {
      "type": "integer",
      "format": "int64"
    },
    "category": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "name": {
      "type": "string",
      "example": "doggie"
    },
    "photoUrls": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "name": {
            "type": "string"
          }
        }
      }
    },
    "status": {
      "type": "string",
      "description": "pet status in the store",
      "enum": [
        "available",
        "pending",
        "sold"
      ]
    }
  }
}

=== prianti29/api-automation-accelerator-playwright/fixtures/addPet.json
[
     {
          "id": 1,
          "category": {
          "id": 1,
          "name": "Dog"
          },
          "name": "doggie",
          "photoUrls": [
               "https://www.shutterstock.com/image-photo/traveler-woman-arms-raised-triumph-on-2457990309"
          ],
          "tags": [
               {
                    "id": 1,
                    "name": "tag1"
               }
          ],
          "status": "available"
     }
]
